issues:
  exclude:
    - "Error return value of `rand.Read` is not checked"
    - "Error return value of `crand.Read` is not checked"
    - "copylocks: call of json.Marshal copies lock value: github.com/project-illium/ilxd/types/blocks.Block contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex"
    - "lostcancel: this return statement may be reached without using the cancel var defined on line 98"
    - "Error return value of `s.processBlock` is not checked"
    - "Error return value of `vc.host.Connect` is not checked"
    - "const `scsNbCodes` is unused"
    - "Error return value of `parser.AddCommand` is not checked"
    - "Error return value of `parser.AddGroup` is not checked"
    - "Error return value of `s.Reset` is not checked"
    - "func `countBits8` is unused"
    - "Error return value of `r.Provide` is not checked"
    - "Error return value of `net.harness.GenerateBlocks` is not checked"
    - "Error return value of `harness2.GenerateBlocks` is not checked"
    - "copylocks: range var out copies lock: github.com/project-illium/ilxd/types/transactions.Output contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex"
    - "Error return value of `logRotator.Write` is not checked"
    - "Error return value of `t.ds.Delete` is not checked"
    - "Error return value of `t.ds.Put` is not checked"
    - "Error return value of `s.wsIndex.RescanViewkey` is not checked"
    - "Error return value of `customStack.Pop` is not checked"
    - "SA4017: ForceReachabilityPublic doesn't have side effects and its return value is ignored"
    - "Error return value of `pds.cachePeerAddrs` is not checked"
    - "Error return value of `ms.lk.Lock` is not checked"
    - "type `printNode` is unused"
    - ".print` is unused"
    - "func `generateBlocksDat` is unused"