// Copyright (c) 2022 Project Illium
// Use of this source code is governed by an MIT
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: message.proto

package wire

import (
	blocks "github.com/project-illium/ilxd/types/blocks"
	transactions "github.com/project-illium/ilxd/types/transactions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResponse int32

const (
	ErrorResponse_None       ErrorResponse = 0
	ErrorResponse_NotFound   ErrorResponse = 1
	ErrorResponse_BadRequest ErrorResponse = 2
	ErrorResponse_NotCurrent ErrorResponse = 3
)

// Enum value maps for ErrorResponse.
var (
	ErrorResponse_name = map[int32]string{
		0: "None",
		1: "NotFound",
		2: "BadRequest",
		3: "NotCurrent",
	}
	ErrorResponse_value = map[string]int32{
		"None":       0,
		"NotFound":   1,
		"BadRequest": 2,
		"NotCurrent": 3,
	}
)

func (x ErrorResponse) Enum() *ErrorResponse {
	p := new(ErrorResponse)
	*p = x
	return p
}

func (x ErrorResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (ErrorResponse) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x ErrorResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorResponse.Descriptor instead.
func (ErrorResponse) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type MsgAvaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request_ID uint32   `protobuf:"varint,1,opt,name=request_ID,json=requestID,proto3" json:"request_ID,omitempty"`
	Invs       [][]byte `protobuf:"bytes,2,rep,name=invs,proto3" json:"invs,omitempty"`
}

func (x *MsgAvaRequest) Reset() {
	*x = MsgAvaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAvaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAvaRequest) ProtoMessage() {}

func (x *MsgAvaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAvaRequest.ProtoReflect.Descriptor instead.
func (*MsgAvaRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MsgAvaRequest) GetRequest_ID() uint32 {
	if x != nil {
		return x.Request_ID
	}
	return 0
}

func (x *MsgAvaRequest) GetInvs() [][]byte {
	if x != nil {
		return x.Invs
	}
	return nil
}

type MsgAvaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request_ID uint32 `protobuf:"varint,1,opt,name=request_ID,json=requestID,proto3" json:"request_ID,omitempty"`
	Votes      []byte `protobuf:"bytes,2,opt,name=votes,proto3" json:"votes,omitempty"`
}

func (x *MsgAvaResponse) Reset() {
	*x = MsgAvaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAvaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAvaResponse) ProtoMessage() {}

func (x *MsgAvaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAvaResponse.ProtoReflect.Descriptor instead.
func (*MsgAvaResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MsgAvaResponse) GetRequest_ID() uint32 {
	if x != nil {
		return x.Request_ID
	}
	return 0
}

func (x *MsgAvaResponse) GetVotes() []byte {
	if x != nil {
		return x.Votes
	}
	return nil
}

type MsgChainServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*MsgChainServiceRequest_GetBlockTxs
	//	*MsgChainServiceRequest_GetBlockTxids
	//	*MsgChainServiceRequest_GetBlock
	//	*MsgChainServiceRequest_GetBlockId
	//	*MsgChainServiceRequest_GetHeadersStream
	//	*MsgChainServiceRequest_GetBlockTxsStream
	//	*MsgChainServiceRequest_GetBest
	Msg isMsgChainServiceRequest_Msg `protobuf_oneof:"msg"`
}

func (x *MsgChainServiceRequest) Reset() {
	*x = MsgChainServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgChainServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgChainServiceRequest) ProtoMessage() {}

func (x *MsgChainServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgChainServiceRequest.ProtoReflect.Descriptor instead.
func (*MsgChainServiceRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (m *MsgChainServiceRequest) GetMsg() isMsgChainServiceRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetBlockTxs() *GetBlockTxsReq {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetBlockTxs); ok {
		return x.GetBlockTxs
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetBlockTxids() *GetBlockTxidsReq {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetBlockTxids); ok {
		return x.GetBlockTxids
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetBlock() *GetBlockReq {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetBlock); ok {
		return x.GetBlock
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetBlockId() *GetBlockIDReq {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetBlockId); ok {
		return x.GetBlockId
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetHeadersStream() *GetHeadersStreamReq {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetHeadersStream); ok {
		return x.GetHeadersStream
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetBlockTxsStream() *GetBlockTxsStreamReq {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetBlockTxsStream); ok {
		return x.GetBlockTxsStream
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetBest() *GetBestReq {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetBest); ok {
		return x.GetBest
	}
	return nil
}

type isMsgChainServiceRequest_Msg interface {
	isMsgChainServiceRequest_Msg()
}

type MsgChainServiceRequest_GetBlockTxs struct {
	GetBlockTxs *GetBlockTxsReq `protobuf:"bytes,1,opt,name=get_block_txs,json=getBlockTxs,proto3,oneof"`
}

type MsgChainServiceRequest_GetBlockTxids struct {
	GetBlockTxids *GetBlockTxidsReq `protobuf:"bytes,2,opt,name=get_block_txids,json=getBlockTxids,proto3,oneof"`
}

type MsgChainServiceRequest_GetBlock struct {
	GetBlock *GetBlockReq `protobuf:"bytes,3,opt,name=get_block,json=getBlock,proto3,oneof"`
}

type MsgChainServiceRequest_GetBlockId struct {
	GetBlockId *GetBlockIDReq `protobuf:"bytes,4,opt,name=get_block_id,json=getBlockId,proto3,oneof"`
}

type MsgChainServiceRequest_GetHeadersStream struct {
	GetHeadersStream *GetHeadersStreamReq `protobuf:"bytes,5,opt,name=get_headers_stream,json=getHeadersStream,proto3,oneof"`
}

type MsgChainServiceRequest_GetBlockTxsStream struct {
	GetBlockTxsStream *GetBlockTxsStreamReq `protobuf:"bytes,6,opt,name=get_block_txs_stream,json=getBlockTxsStream,proto3,oneof"`
}

type MsgChainServiceRequest_GetBest struct {
	GetBest *GetBestReq `protobuf:"bytes,7,opt,name=get_best,json=getBest,proto3,oneof"`
}

func (*MsgChainServiceRequest_GetBlockTxs) isMsgChainServiceRequest_Msg() {}

func (*MsgChainServiceRequest_GetBlockTxids) isMsgChainServiceRequest_Msg() {}

func (*MsgChainServiceRequest_GetBlock) isMsgChainServiceRequest_Msg() {}

func (*MsgChainServiceRequest_GetBlockId) isMsgChainServiceRequest_Msg() {}

func (*MsgChainServiceRequest_GetHeadersStream) isMsgChainServiceRequest_Msg() {}

func (*MsgChainServiceRequest_GetBlockTxsStream) isMsgChainServiceRequest_Msg() {}

func (*MsgChainServiceRequest_GetBest) isMsgChainServiceRequest_Msg() {}

type GetBlockTxsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block_ID  []byte   `protobuf:"bytes,1,opt,name=block_ID,json=blockID,proto3" json:"block_ID,omitempty"`
	TxIndexes []uint32 `protobuf:"varint,2,rep,packed,name=tx_indexes,json=txIndexes,proto3" json:"tx_indexes,omitempty"`
}

func (x *GetBlockTxsReq) Reset() {
	*x = GetBlockTxsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockTxsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTxsReq) ProtoMessage() {}

func (x *GetBlockTxsReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTxsReq.ProtoReflect.Descriptor instead.
func (*GetBlockTxsReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockTxsReq) GetBlock_ID() []byte {
	if x != nil {
		return x.Block_ID
	}
	return nil
}

func (x *GetBlockTxsReq) GetTxIndexes() []uint32 {
	if x != nil {
		return x.TxIndexes
	}
	return nil
}

type MsgBlockTxsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*transactions.Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Error        ErrorResponse               `protobuf:"varint,2,opt,name=error,proto3,enum=ErrorResponse" json:"error,omitempty"`
}

func (x *MsgBlockTxsResp) Reset() {
	*x = MsgBlockTxsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBlockTxsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBlockTxsResp) ProtoMessage() {}

func (x *MsgBlockTxsResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBlockTxsResp.ProtoReflect.Descriptor instead.
func (*MsgBlockTxsResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *MsgBlockTxsResp) GetTransactions() []*transactions.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *MsgBlockTxsResp) GetError() ErrorResponse {
	if x != nil {
		return x.Error
	}
	return ErrorResponse_None
}

type GetBlockTxidsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block_ID []byte `protobuf:"bytes,1,opt,name=block_ID,json=blockID,proto3" json:"block_ID,omitempty"`
}

func (x *GetBlockTxidsReq) Reset() {
	*x = GetBlockTxidsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockTxidsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTxidsReq) ProtoMessage() {}

func (x *GetBlockTxidsReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTxidsReq.ProtoReflect.Descriptor instead.
func (*GetBlockTxidsReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlockTxidsReq) GetBlock_ID() []byte {
	if x != nil {
		return x.Block_ID
	}
	return nil
}

type MsgBlockTxidsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txids [][]byte      `protobuf:"bytes,1,rep,name=txids,proto3" json:"txids,omitempty"`
	Error ErrorResponse `protobuf:"varint,2,opt,name=error,proto3,enum=ErrorResponse" json:"error,omitempty"`
}

func (x *MsgBlockTxidsResp) Reset() {
	*x = MsgBlockTxidsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBlockTxidsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBlockTxidsResp) ProtoMessage() {}

func (x *MsgBlockTxidsResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBlockTxidsResp.ProtoReflect.Descriptor instead.
func (*MsgBlockTxidsResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *MsgBlockTxidsResp) GetTxids() [][]byte {
	if x != nil {
		return x.Txids
	}
	return nil
}

func (x *MsgBlockTxidsResp) GetError() ErrorResponse {
	if x != nil {
		return x.Error
	}
	return ErrorResponse_None
}

type GetBlockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block_ID []byte `protobuf:"bytes,1,opt,name=block_ID,json=blockID,proto3" json:"block_ID,omitempty"`
}

func (x *GetBlockReq) Reset() {
	*x = GetBlockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockReq) ProtoMessage() {}

func (x *GetBlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockReq.ProtoReflect.Descriptor instead.
func (*GetBlockReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlockReq) GetBlock_ID() []byte {
	if x != nil {
		return x.Block_ID
	}
	return nil
}

type MsgBlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *blocks.Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Error ErrorResponse `protobuf:"varint,2,opt,name=error,proto3,enum=ErrorResponse" json:"error,omitempty"`
}

func (x *MsgBlockResp) Reset() {
	*x = MsgBlockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBlockResp) ProtoMessage() {}

func (x *MsgBlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBlockResp.ProtoReflect.Descriptor instead.
func (*MsgBlockResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *MsgBlockResp) GetBlock() *blocks.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *MsgBlockResp) GetError() ErrorResponse {
	if x != nil {
		return x.Error
	}
	return ErrorResponse_None
}

type GetBlockIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height uint32 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetBlockIDReq) Reset() {
	*x = GetBlockIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockIDReq) ProtoMessage() {}

func (x *GetBlockIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockIDReq.ProtoReflect.Descriptor instead.
func (*GetBlockIDReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetBlockIDReq) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type MsgGetBlockIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block_ID []byte        `protobuf:"bytes,1,opt,name=block_ID,json=blockID,proto3" json:"block_ID,omitempty"`
	Error    ErrorResponse `protobuf:"varint,2,opt,name=error,proto3,enum=ErrorResponse" json:"error,omitempty"`
}

func (x *MsgGetBlockIDResp) Reset() {
	*x = MsgGetBlockIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetBlockIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetBlockIDResp) ProtoMessage() {}

func (x *MsgGetBlockIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetBlockIDResp.ProtoReflect.Descriptor instead.
func (*MsgGetBlockIDResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *MsgGetBlockIDResp) GetBlock_ID() []byte {
	if x != nil {
		return x.Block_ID
	}
	return nil
}

func (x *MsgGetBlockIDResp) GetError() ErrorResponse {
	if x != nil {
		return x.Error
	}
	return ErrorResponse_None
}

type GetHeadersStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartHeight uint32 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
}

func (x *GetHeadersStreamReq) Reset() {
	*x = GetHeadersStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHeadersStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadersStreamReq) ProtoMessage() {}

func (x *GetHeadersStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadersStreamReq.ProtoReflect.Descriptor instead.
func (*GetHeadersStreamReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *GetHeadersStreamReq) GetStartHeight() uint32 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

type GetBlockTxsStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartHeight uint32 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
}

func (x *GetBlockTxsStreamReq) Reset() {
	*x = GetBlockTxsStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockTxsStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTxsStreamReq) ProtoMessage() {}

func (x *GetBlockTxsStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTxsStreamReq.ProtoReflect.Descriptor instead.
func (*GetBlockTxsStreamReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlockTxsStreamReq) GetStartHeight() uint32 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

type GetBestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBestReq) Reset() {
	*x = GetBestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestReq) ProtoMessage() {}

func (x *GetBestReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestReq.ProtoReflect.Descriptor instead.
func (*GetBestReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

type MsgGetBestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block_ID []byte        `protobuf:"bytes,1,opt,name=block_ID,json=blockID,proto3" json:"block_ID,omitempty"`
	Height   uint32        `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Error    ErrorResponse `protobuf:"varint,3,opt,name=error,proto3,enum=ErrorResponse" json:"error,omitempty"`
}

func (x *MsgGetBestResp) Reset() {
	*x = MsgGetBestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetBestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetBestResp) ProtoMessage() {}

func (x *MsgGetBestResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetBestResp.ProtoReflect.Descriptor instead.
func (*MsgGetBestResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{14}
}

func (x *MsgGetBestResp) GetBlock_ID() []byte {
	if x != nil {
		return x.Block_ID
	}
	return nil
}

func (x *MsgGetBestResp) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MsgGetBestResp) GetError() ErrorResponse {
	if x != nil {
		return x.Error
	}
	return ErrorResponse_None
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x42, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x41, 0x76, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x76, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x04, 0x69, 0x6e, 0x76, 0x73, 0x22, 0x45, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x41, 0x76, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x22, 0xae, 0x03, 0x0a,
	0x16, 0x4d, 0x73, 0x67, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x5f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x78, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x52, 0x65, 0x71, 0x48,
	0x00, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x12, 0x3b,
	0x0a, 0x0f, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x78, 0x69, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x54, 0x78, 0x69, 0x64, 0x73, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x69, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x67,
	0x65, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x08,
	0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x32, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x71, 0x48, 0x00,
	0x52, 0x0a, 0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x44, 0x0a, 0x12,
	0x67, 0x65, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x48, 0x00,
	0x52, 0x10, 0x67, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x48, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x74, 0x78, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x11, 0x67, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x28, 0x0a, 0x08,
	0x67, 0x65, 0x74, 0x5f, 0x62, 0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x07, 0x67,
	0x65, 0x74, 0x42, 0x65, 0x73, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4a, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x78,
	0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09,
	0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x22, 0x69, 0x0a, 0x0f, 0x4d, 0x73, 0x67,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0c,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x54, 0x78, 0x69, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x44, 0x22, 0x4f, 0x0a, 0x11, 0x4d, 0x73, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54,
	0x78, 0x69, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x78, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x78, 0x69, 0x64, 0x73, 0x12, 0x24,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x28, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x22, 0x52,
	0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c,
	0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x27, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x54, 0x0a, 0x11, 0x4d,
	0x73, 0x67, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x38, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x39, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x22, 0x69, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x42, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a,
	0x47, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f,
	0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x77,
	0x69, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_message_proto_goTypes = []interface{}{
	(ErrorResponse)(0),               // 0: ErrorResponse
	(*MsgAvaRequest)(nil),            // 1: MsgAvaRequest
	(*MsgAvaResponse)(nil),           // 2: MsgAvaResponse
	(*MsgChainServiceRequest)(nil),   // 3: MsgChainServiceRequest
	(*GetBlockTxsReq)(nil),           // 4: GetBlockTxsReq
	(*MsgBlockTxsResp)(nil),          // 5: MsgBlockTxsResp
	(*GetBlockTxidsReq)(nil),         // 6: GetBlockTxidsReq
	(*MsgBlockTxidsResp)(nil),        // 7: MsgBlockTxidsResp
	(*GetBlockReq)(nil),              // 8: GetBlockReq
	(*MsgBlockResp)(nil),             // 9: MsgBlockResp
	(*GetBlockIDReq)(nil),            // 10: GetBlockIDReq
	(*MsgGetBlockIDResp)(nil),        // 11: MsgGetBlockIDResp
	(*GetHeadersStreamReq)(nil),      // 12: GetHeadersStreamReq
	(*GetBlockTxsStreamReq)(nil),     // 13: GetBlockTxsStreamReq
	(*GetBestReq)(nil),               // 14: GetBestReq
	(*MsgGetBestResp)(nil),           // 15: MsgGetBestResp
	(*transactions.Transaction)(nil), // 16: Transaction
	(*blocks.Block)(nil),             // 17: Block
}
var file_message_proto_depIdxs = []int32{
	4,  // 0: MsgChainServiceRequest.get_block_txs:type_name -> GetBlockTxsReq
	6,  // 1: MsgChainServiceRequest.get_block_txids:type_name -> GetBlockTxidsReq
	8,  // 2: MsgChainServiceRequest.get_block:type_name -> GetBlockReq
	10, // 3: MsgChainServiceRequest.get_block_id:type_name -> GetBlockIDReq
	12, // 4: MsgChainServiceRequest.get_headers_stream:type_name -> GetHeadersStreamReq
	13, // 5: MsgChainServiceRequest.get_block_txs_stream:type_name -> GetBlockTxsStreamReq
	14, // 6: MsgChainServiceRequest.get_best:type_name -> GetBestReq
	16, // 7: MsgBlockTxsResp.transactions:type_name -> Transaction
	0,  // 8: MsgBlockTxsResp.error:type_name -> ErrorResponse
	0,  // 9: MsgBlockTxidsResp.error:type_name -> ErrorResponse
	17, // 10: MsgBlockResp.block:type_name -> Block
	0,  // 11: MsgBlockResp.error:type_name -> ErrorResponse
	0,  // 12: MsgGetBlockIDResp.error:type_name -> ErrorResponse
	0,  // 13: MsgGetBestResp.error:type_name -> ErrorResponse
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAvaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAvaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgChainServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockTxsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBlockTxsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockTxidsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBlockTxidsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBlockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetBlockIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHeadersStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockTxsStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetBestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*MsgChainServiceRequest_GetBlockTxs)(nil),
		(*MsgChainServiceRequest_GetBlockTxids)(nil),
		(*MsgChainServiceRequest_GetBlock)(nil),
		(*MsgChainServiceRequest_GetBlockId)(nil),
		(*MsgChainServiceRequest_GetHeadersStream)(nil),
		(*MsgChainServiceRequest_GetBlockTxsStream)(nil),
		(*MsgChainServiceRequest_GetBest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
