// Copyright (c) 2022 Project Illium
// Use of this source code is governed by an MIT
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: message.proto

package wire

import (
	"github.com/project-illium/ilxd/types/transactions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResponse int32

const (
	ErrorResponse_None       ErrorResponse = 0
	ErrorResponse_NotFound   ErrorResponse = 1
	ErrorResponse_BadRequest ErrorResponse = 2
)

// Enum value maps for ErrorResponse.
var (
	ErrorResponse_name = map[int32]string{
		0: "None",
		1: "NotFound",
		2: "BadRequest",
	}
	ErrorResponse_value = map[string]int32{
		"None":       0,
		"NotFound":   1,
		"BadRequest": 2,
	}
)

func (x ErrorResponse) Enum() *ErrorResponse {
	p := new(ErrorResponse)
	*p = x
	return p
}

func (x ErrorResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (ErrorResponse) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x ErrorResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorResponse.Descriptor instead.
func (ErrorResponse) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type MsgAvaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID uint32   `protobuf:"varint,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Invs      [][]byte `protobuf:"bytes,2,rep,name=invs,proto3" json:"invs,omitempty"`
}

func (x *MsgAvaRequest) Reset() {
	*x = MsgAvaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAvaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAvaRequest) ProtoMessage() {}

func (x *MsgAvaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAvaRequest.ProtoReflect.Descriptor instead.
func (*MsgAvaRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MsgAvaRequest) GetRequestID() uint32 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

func (x *MsgAvaRequest) GetInvs() [][]byte {
	if x != nil {
		return x.Invs
	}
	return nil
}

type MsgAvaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID uint32 `protobuf:"varint,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Votes     []byte `protobuf:"bytes,2,opt,name=votes,proto3" json:"votes,omitempty"`
}

func (x *MsgAvaResponse) Reset() {
	*x = MsgAvaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAvaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAvaResponse) ProtoMessage() {}

func (x *MsgAvaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAvaResponse.ProtoReflect.Descriptor instead.
func (*MsgAvaResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MsgAvaResponse) GetRequestID() uint32 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

func (x *MsgAvaResponse) GetVotes() []byte {
	if x != nil {
		return x.Votes
	}
	return nil
}

type MsgChainServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*MsgChainServiceRequest_GetBlockTxs
	//	*MsgChainServiceRequest_GetBlockTxids
	Msg isMsgChainServiceRequest_Msg `protobuf_oneof:"msg"`
}

func (x *MsgChainServiceRequest) Reset() {
	*x = MsgChainServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgChainServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgChainServiceRequest) ProtoMessage() {}

func (x *MsgChainServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgChainServiceRequest.ProtoReflect.Descriptor instead.
func (*MsgChainServiceRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (m *MsgChainServiceRequest) GetMsg() isMsgChainServiceRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetBlockTxs() *GetBlockTxs {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetBlockTxs); ok {
		return x.GetBlockTxs
	}
	return nil
}

func (x *MsgChainServiceRequest) GetGetBlockTxids() *GetBlockTxids {
	if x, ok := x.GetMsg().(*MsgChainServiceRequest_GetBlockTxids); ok {
		return x.GetBlockTxids
	}
	return nil
}

type isMsgChainServiceRequest_Msg interface {
	isMsgChainServiceRequest_Msg()
}

type MsgChainServiceRequest_GetBlockTxs struct {
	GetBlockTxs *GetBlockTxs `protobuf:"bytes,1,opt,name=get_block_txs,json=getBlockTxs,proto3,oneof"`
}

type MsgChainServiceRequest_GetBlockTxids struct {
	GetBlockTxids *GetBlockTxids `protobuf:"bytes,2,opt,name=get_block_txids,json=getBlockTxids,proto3,oneof"`
}

func (*MsgChainServiceRequest_GetBlockTxs) isMsgChainServiceRequest_Msg() {}

func (*MsgChainServiceRequest_GetBlockTxids) isMsgChainServiceRequest_Msg() {}

type GetBlockTxs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockID   []byte   `protobuf:"bytes,1,opt,name=blockID,proto3" json:"blockID,omitempty"`
	TxIndexes []uint32 `protobuf:"varint,2,rep,packed,name=txIndexes,proto3" json:"txIndexes,omitempty"`
}

func (x *GetBlockTxs) Reset() {
	*x = GetBlockTxs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockTxs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTxs) ProtoMessage() {}

func (x *GetBlockTxs) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTxs.ProtoReflect.Descriptor instead.
func (*GetBlockTxs) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockTxs) GetBlockID() []byte {
	if x != nil {
		return x.BlockID
	}
	return nil
}

func (x *GetBlockTxs) GetTxIndexes() []uint32 {
	if x != nil {
		return x.TxIndexes
	}
	return nil
}

type MsgBlockTxs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*transactions.Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Error        ErrorResponse               `protobuf:"varint,2,opt,name=error,proto3,enum=ErrorResponse" json:"error,omitempty"`
}

func (x *MsgBlockTxs) Reset() {
	*x = MsgBlockTxs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBlockTxs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBlockTxs) ProtoMessage() {}

func (x *MsgBlockTxs) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBlockTxs.ProtoReflect.Descriptor instead.
func (*MsgBlockTxs) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *MsgBlockTxs) GetTransactions() []*transactions.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *MsgBlockTxs) GetError() ErrorResponse {
	if x != nil {
		return x.Error
	}
	return ErrorResponse_None
}

type GetBlockTxids struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockID []byte `protobuf:"bytes,1,opt,name=blockID,proto3" json:"blockID,omitempty"`
}

func (x *GetBlockTxids) Reset() {
	*x = GetBlockTxids{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockTxids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTxids) ProtoMessage() {}

func (x *GetBlockTxids) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTxids.ProtoReflect.Descriptor instead.
func (*GetBlockTxids) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlockTxids) GetBlockID() []byte {
	if x != nil {
		return x.BlockID
	}
	return nil
}

type MsgBlockTxids struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txids [][]byte      `protobuf:"bytes,1,rep,name=txids,proto3" json:"txids,omitempty"`
	Error ErrorResponse `protobuf:"varint,2,opt,name=error,proto3,enum=ErrorResponse" json:"error,omitempty"`
}

func (x *MsgBlockTxids) Reset() {
	*x = MsgBlockTxids{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBlockTxids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBlockTxids) ProtoMessage() {}

func (x *MsgBlockTxids) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBlockTxids.ProtoReflect.Descriptor instead.
func (*MsgBlockTxids) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *MsgBlockTxids) GetTxids() [][]byte {
	if x != nil {
		return x.Txids
	}
	return nil
}

func (x *MsgBlockTxids) GetError() ErrorResponse {
	if x != nil {
		return x.Error
	}
	return ErrorResponse_None
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x41, 0x76, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x76, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x69, 0x6e, 0x76, 0x73, 0x22, 0x44, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x41, 0x76, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x8d, 0x01, 0x0a,
	0x16, 0x4d, 0x73, 0x67, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x5f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x78, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x48, 0x00, 0x52, 0x0b,
	0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x12, 0x38, 0x0a, 0x0f, 0x67,
	0x65, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x78, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54,
	0x78, 0x69, 0x64, 0x73, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x54, 0x78, 0x69, 0x64, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x65, 0x73, 0x22, 0x65, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54,
	0x78, 0x73, 0x12, 0x30, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x29, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x69, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x44, 0x22, 0x4b, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x54, 0x78, 0x69, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x78, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x78, 0x69, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x2a, 0x37, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x02, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2e, 0x2f, 0x77, 0x69, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_proto_goTypes = []interface{}{
	(ErrorResponse)(0),               // 0: ErrorResponse
	(*MsgAvaRequest)(nil),            // 1: MsgAvaRequest
	(*MsgAvaResponse)(nil),           // 2: MsgAvaResponse
	(*MsgChainServiceRequest)(nil),   // 3: MsgChainServiceRequest
	(*GetBlockTxs)(nil),              // 4: GetBlockTxs
	(*MsgBlockTxs)(nil),              // 5: MsgBlockTxs
	(*GetBlockTxids)(nil),            // 6: GetBlockTxids
	(*MsgBlockTxids)(nil),            // 7: MsgBlockTxids
	(*transactions.Transaction)(nil), // 8: Transaction
}
var file_message_proto_depIdxs = []int32{
	4, // 0: MsgChainServiceRequest.get_block_txs:type_name -> GetBlockTxs
	6, // 1: MsgChainServiceRequest.get_block_txids:type_name -> GetBlockTxids
	8, // 2: MsgBlockTxs.transactions:type_name -> Transaction
	0, // 3: MsgBlockTxs.error:type_name -> ErrorResponse
	0, // 4: MsgBlockTxids.error:type_name -> ErrorResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAvaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAvaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgChainServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockTxs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBlockTxs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockTxids); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBlockTxids); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*MsgChainServiceRequest_GetBlockTxs)(nil),
		(*MsgChainServiceRequest_GetBlockTxids)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
