// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: ilxrpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlockchainServiceClient is the client API for BlockchainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainServiceClient interface {
	// GetMempoolInfo returns the state of the current mempool
	GetMempoolInfo(ctx context.Context, in *GetMempoolInfoRequest, opts ...grpc.CallOption) (*GetMempoolInfoResponse, error)
	// GetMempool returns all the transactions in the mempool
	GetMempool(ctx context.Context, in *GetMempoolRequest, opts ...grpc.CallOption) (*GetMempoolResponse, error)
	// GetBlockchainInfo returns data about the blockchain including the most recent
	// block hash and height.
	GetBlockchainInfo(ctx context.Context, in *GetBlockchainInfoRequest, opts ...grpc.CallOption) (*GetBlockchainInfoResponse, error)
	// GetBlockInfo returns a BlockHeader plus some extra metadata.
	GetBlockInfo(ctx context.Context, in *GetBlockInfoRequest, opts ...grpc.CallOption) (*GetBlockInfoResponse, error)
	// GetBlock returns the detailed data for a block.
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	// GetCompressedBlock returns a block that is stripped down to just the outputs.
	// It is the bare minimum information a client side wallet needs to compute its internal
	// state.
	GetCompressedBlock(ctx context.Context, in *GetCompressedBlockRequest, opts ...grpc.CallOption) (*GetCompressedBlockResponse, error)
	// GetHeaders returns a batch of headers according to the request parameters.
	GetHeaders(ctx context.Context, in *GetHeadersRequest, opts ...grpc.CallOption) (*GetHeadersResponse, error)
	// GetCompressedBlocks returns a batch of CompressedBlocks according to the request parameters.
	GetCompressedBlocks(ctx context.Context, in *GetCompressedBlocksRequest, opts ...grpc.CallOption) (*GetCompressedBlocksResponse, error)
	// GetTransaction returns the transaction for the given transaction ID.
	//
	// **Requires TxIndex**
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	// GetMerkleProof returns a Merkle (SPV) proof for a specific transaction
	// in the provided block.
	//
	// **Requires TxIndex**
	GetMerkleProof(ctx context.Context, in *GetMerkleProofRequest, opts ...grpc.CallOption) (*GetMerkleProofResponse, error)
	// GetValidator returns all the information about the given validator including number
	// of staked coins.
	GetValidator(ctx context.Context, in *GetValidatorRequest, opts ...grpc.CallOption) (*GetValidatorResponse, error)
	// GetValidatorSetInfo returns information about the validator set.
	GetValidatorSetInfo(ctx context.Context, in *GetValidatorSetInfoRequest, opts ...grpc.CallOption) (*GetValidatorSetInfoResponse, error)
	// GetValidatorSet returns all the validators in the current validator set.
	GetValidatorSet(ctx context.Context, in *GetValidatorSetRequest, opts ...grpc.CallOption) (*GetValidatorSetResponse, error)
	// GetAccumulatorCheckpoint returns the accumulator at the requested height.
	// If there is no checkpoint at that height, the *next* checkpoint found in the
	// chain will be returned.
	GetAccumulatorCheckpoint(ctx context.Context, in *GetAccumulatorCheckpointRequest, opts ...grpc.CallOption) (*GetAccumulatorCheckpointResponse, error)
	// SubmitTransaction validates a transaction and submits it to the network. An error will be returned
	// if it fails validation.
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error)
	// SubscribeBlocks returns a stream of notifications when new blocks are finalized and
	// connected to the chain.
	SubscribeBlocks(ctx context.Context, in *SubscribeBlocksRequest, opts ...grpc.CallOption) (BlockchainService_SubscribeBlocksClient, error)
}

type blockchainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainServiceClient(cc grpc.ClientConnInterface) BlockchainServiceClient {
	return &blockchainServiceClient{cc}
}

func (c *blockchainServiceClient) GetMempoolInfo(ctx context.Context, in *GetMempoolInfoRequest, opts ...grpc.CallOption) (*GetMempoolInfoResponse, error) {
	out := new(GetMempoolInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetMempoolInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetMempool(ctx context.Context, in *GetMempoolRequest, opts ...grpc.CallOption) (*GetMempoolResponse, error) {
	out := new(GetMempoolResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetMempool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetBlockchainInfo(ctx context.Context, in *GetBlockchainInfoRequest, opts ...grpc.CallOption) (*GetBlockchainInfoResponse, error) {
	out := new(GetBlockchainInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetBlockchainInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetBlockInfo(ctx context.Context, in *GetBlockInfoRequest, opts ...grpc.CallOption) (*GetBlockInfoResponse, error) {
	out := new(GetBlockInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetBlockInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetCompressedBlock(ctx context.Context, in *GetCompressedBlockRequest, opts ...grpc.CallOption) (*GetCompressedBlockResponse, error) {
	out := new(GetCompressedBlockResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetCompressedBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetHeaders(ctx context.Context, in *GetHeadersRequest, opts ...grpc.CallOption) (*GetHeadersResponse, error) {
	out := new(GetHeadersResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetHeaders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetCompressedBlocks(ctx context.Context, in *GetCompressedBlocksRequest, opts ...grpc.CallOption) (*GetCompressedBlocksResponse, error) {
	out := new(GetCompressedBlocksResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetCompressedBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetMerkleProof(ctx context.Context, in *GetMerkleProofRequest, opts ...grpc.CallOption) (*GetMerkleProofResponse, error) {
	out := new(GetMerkleProofResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetMerkleProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetValidator(ctx context.Context, in *GetValidatorRequest, opts ...grpc.CallOption) (*GetValidatorResponse, error) {
	out := new(GetValidatorResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetValidator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetValidatorSetInfo(ctx context.Context, in *GetValidatorSetInfoRequest, opts ...grpc.CallOption) (*GetValidatorSetInfoResponse, error) {
	out := new(GetValidatorSetInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetValidatorSetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetValidatorSet(ctx context.Context, in *GetValidatorSetRequest, opts ...grpc.CallOption) (*GetValidatorSetResponse, error) {
	out := new(GetValidatorSetResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetValidatorSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetAccumulatorCheckpoint(ctx context.Context, in *GetAccumulatorCheckpointRequest, opts ...grpc.CallOption) (*GetAccumulatorCheckpointResponse, error) {
	out := new(GetAccumulatorCheckpointResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/GetAccumulatorCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error) {
	out := new(SubmitTransactionResponse)
	err := c.cc.Invoke(ctx, "/pb.BlockchainService/SubmitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) SubscribeBlocks(ctx context.Context, in *SubscribeBlocksRequest, opts ...grpc.CallOption) (BlockchainService_SubscribeBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &BlockchainService_ServiceDesc.Streams[0], "/pb.BlockchainService/SubscribeBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &blockchainServiceSubscribeBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlockchainService_SubscribeBlocksClient interface {
	Recv() (*BlockNotification, error)
	grpc.ClientStream
}

type blockchainServiceSubscribeBlocksClient struct {
	grpc.ClientStream
}

func (x *blockchainServiceSubscribeBlocksClient) Recv() (*BlockNotification, error) {
	m := new(BlockNotification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlockchainServiceServer is the server API for BlockchainService service.
// All implementations must embed UnimplementedBlockchainServiceServer
// for forward compatibility
type BlockchainServiceServer interface {
	// GetMempoolInfo returns the state of the current mempool
	GetMempoolInfo(context.Context, *GetMempoolInfoRequest) (*GetMempoolInfoResponse, error)
	// GetMempool returns all the transactions in the mempool
	GetMempool(context.Context, *GetMempoolRequest) (*GetMempoolResponse, error)
	// GetBlockchainInfo returns data about the blockchain including the most recent
	// block hash and height.
	GetBlockchainInfo(context.Context, *GetBlockchainInfoRequest) (*GetBlockchainInfoResponse, error)
	// GetBlockInfo returns a BlockHeader plus some extra metadata.
	GetBlockInfo(context.Context, *GetBlockInfoRequest) (*GetBlockInfoResponse, error)
	// GetBlock returns the detailed data for a block.
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	// GetCompressedBlock returns a block that is stripped down to just the outputs.
	// It is the bare minimum information a client side wallet needs to compute its internal
	// state.
	GetCompressedBlock(context.Context, *GetCompressedBlockRequest) (*GetCompressedBlockResponse, error)
	// GetHeaders returns a batch of headers according to the request parameters.
	GetHeaders(context.Context, *GetHeadersRequest) (*GetHeadersResponse, error)
	// GetCompressedBlocks returns a batch of CompressedBlocks according to the request parameters.
	GetCompressedBlocks(context.Context, *GetCompressedBlocksRequest) (*GetCompressedBlocksResponse, error)
	// GetTransaction returns the transaction for the given transaction ID.
	//
	// **Requires TxIndex**
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// GetMerkleProof returns a Merkle (SPV) proof for a specific transaction
	// in the provided block.
	//
	// **Requires TxIndex**
	GetMerkleProof(context.Context, *GetMerkleProofRequest) (*GetMerkleProofResponse, error)
	// GetValidator returns all the information about the given validator including number
	// of staked coins.
	GetValidator(context.Context, *GetValidatorRequest) (*GetValidatorResponse, error)
	// GetValidatorSetInfo returns information about the validator set.
	GetValidatorSetInfo(context.Context, *GetValidatorSetInfoRequest) (*GetValidatorSetInfoResponse, error)
	// GetValidatorSet returns all the validators in the current validator set.
	GetValidatorSet(context.Context, *GetValidatorSetRequest) (*GetValidatorSetResponse, error)
	// GetAccumulatorCheckpoint returns the accumulator at the requested height.
	// If there is no checkpoint at that height, the *next* checkpoint found in the
	// chain will be returned.
	GetAccumulatorCheckpoint(context.Context, *GetAccumulatorCheckpointRequest) (*GetAccumulatorCheckpointResponse, error)
	// SubmitTransaction validates a transaction and submits it to the network. An error will be returned
	// if it fails validation.
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error)
	// SubscribeBlocks returns a stream of notifications when new blocks are finalized and
	// connected to the chain.
	SubscribeBlocks(*SubscribeBlocksRequest, BlockchainService_SubscribeBlocksServer) error
	mustEmbedUnimplementedBlockchainServiceServer()
}

// UnimplementedBlockchainServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBlockchainServiceServer struct {
}

func (UnimplementedBlockchainServiceServer) GetMempoolInfo(context.Context, *GetMempoolInfoRequest) (*GetMempoolInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMempoolInfo not implemented")
}
func (UnimplementedBlockchainServiceServer) GetMempool(context.Context, *GetMempoolRequest) (*GetMempoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMempool not implemented")
}
func (UnimplementedBlockchainServiceServer) GetBlockchainInfo(context.Context, *GetBlockchainInfoRequest) (*GetBlockchainInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockchainInfo not implemented")
}
func (UnimplementedBlockchainServiceServer) GetBlockInfo(context.Context, *GetBlockInfoRequest) (*GetBlockInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockInfo not implemented")
}
func (UnimplementedBlockchainServiceServer) GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedBlockchainServiceServer) GetCompressedBlock(context.Context, *GetCompressedBlockRequest) (*GetCompressedBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompressedBlock not implemented")
}
func (UnimplementedBlockchainServiceServer) GetHeaders(context.Context, *GetHeadersRequest) (*GetHeadersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHeaders not implemented")
}
func (UnimplementedBlockchainServiceServer) GetCompressedBlocks(context.Context, *GetCompressedBlocksRequest) (*GetCompressedBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompressedBlocks not implemented")
}
func (UnimplementedBlockchainServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedBlockchainServiceServer) GetMerkleProof(context.Context, *GetMerkleProofRequest) (*GetMerkleProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMerkleProof not implemented")
}
func (UnimplementedBlockchainServiceServer) GetValidator(context.Context, *GetValidatorRequest) (*GetValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidator not implemented")
}
func (UnimplementedBlockchainServiceServer) GetValidatorSetInfo(context.Context, *GetValidatorSetInfoRequest) (*GetValidatorSetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorSetInfo not implemented")
}
func (UnimplementedBlockchainServiceServer) GetValidatorSet(context.Context, *GetValidatorSetRequest) (*GetValidatorSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorSet not implemented")
}
func (UnimplementedBlockchainServiceServer) GetAccumulatorCheckpoint(context.Context, *GetAccumulatorCheckpointRequest) (*GetAccumulatorCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccumulatorCheckpoint not implemented")
}
func (UnimplementedBlockchainServiceServer) SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedBlockchainServiceServer) SubscribeBlocks(*SubscribeBlocksRequest, BlockchainService_SubscribeBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeBlocks not implemented")
}
func (UnimplementedBlockchainServiceServer) mustEmbedUnimplementedBlockchainServiceServer() {}

// UnsafeBlockchainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainServiceServer will
// result in compilation errors.
type UnsafeBlockchainServiceServer interface {
	mustEmbedUnimplementedBlockchainServiceServer()
}

func RegisterBlockchainServiceServer(s grpc.ServiceRegistrar, srv BlockchainServiceServer) {
	s.RegisterService(&BlockchainService_ServiceDesc, srv)
}

func _BlockchainService_GetMempoolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMempoolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetMempoolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetMempoolInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetMempoolInfo(ctx, req.(*GetMempoolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetMempool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMempoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetMempool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetMempool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetMempool(ctx, req.(*GetMempoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetBlockchainInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockchainInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetBlockchainInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetBlockchainInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetBlockchainInfo(ctx, req.(*GetBlockchainInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetBlockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetBlockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetBlockInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetBlockInfo(ctx, req.(*GetBlockInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetCompressedBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompressedBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetCompressedBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetCompressedBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetCompressedBlock(ctx, req.(*GetCompressedBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeadersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetHeaders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetHeaders(ctx, req.(*GetHeadersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetCompressedBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompressedBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetCompressedBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetCompressedBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetCompressedBlocks(ctx, req.(*GetCompressedBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetMerkleProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerkleProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetMerkleProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetMerkleProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetMerkleProof(ctx, req.(*GetMerkleProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetValidator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetValidator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetValidator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetValidator(ctx, req.(*GetValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetValidatorSetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorSetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetValidatorSetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetValidatorSetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetValidatorSetInfo(ctx, req.(*GetValidatorSetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetValidatorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetValidatorSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetValidatorSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetValidatorSet(ctx, req.(*GetValidatorSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetAccumulatorCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccumulatorCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetAccumulatorCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/GetAccumulatorCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetAccumulatorCheckpoint(ctx, req.(*GetAccumulatorCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockchainService/SubmitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_SubscribeBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockchainServiceServer).SubscribeBlocks(m, &blockchainServiceSubscribeBlocksServer{stream})
}

type BlockchainService_SubscribeBlocksServer interface {
	Send(*BlockNotification) error
	grpc.ServerStream
}

type blockchainServiceSubscribeBlocksServer struct {
	grpc.ServerStream
}

func (x *blockchainServiceSubscribeBlocksServer) Send(m *BlockNotification) error {
	return x.ServerStream.SendMsg(m)
}

// BlockchainService_ServiceDesc is the grpc.ServiceDesc for BlockchainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BlockchainService",
	HandlerType: (*BlockchainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMempoolInfo",
			Handler:    _BlockchainService_GetMempoolInfo_Handler,
		},
		{
			MethodName: "GetMempool",
			Handler:    _BlockchainService_GetMempool_Handler,
		},
		{
			MethodName: "GetBlockchainInfo",
			Handler:    _BlockchainService_GetBlockchainInfo_Handler,
		},
		{
			MethodName: "GetBlockInfo",
			Handler:    _BlockchainService_GetBlockInfo_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _BlockchainService_GetBlock_Handler,
		},
		{
			MethodName: "GetCompressedBlock",
			Handler:    _BlockchainService_GetCompressedBlock_Handler,
		},
		{
			MethodName: "GetHeaders",
			Handler:    _BlockchainService_GetHeaders_Handler,
		},
		{
			MethodName: "GetCompressedBlocks",
			Handler:    _BlockchainService_GetCompressedBlocks_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _BlockchainService_GetTransaction_Handler,
		},
		{
			MethodName: "GetMerkleProof",
			Handler:    _BlockchainService_GetMerkleProof_Handler,
		},
		{
			MethodName: "GetValidator",
			Handler:    _BlockchainService_GetValidator_Handler,
		},
		{
			MethodName: "GetValidatorSetInfo",
			Handler:    _BlockchainService_GetValidatorSetInfo_Handler,
		},
		{
			MethodName: "GetValidatorSet",
			Handler:    _BlockchainService_GetValidatorSet_Handler,
		},
		{
			MethodName: "GetAccumulatorCheckpoint",
			Handler:    _BlockchainService_GetAccumulatorCheckpoint_Handler,
		},
		{
			MethodName: "SubmitTransaction",
			Handler:    _BlockchainService_SubmitTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeBlocks",
			Handler:       _BlockchainService_SubscribeBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ilxrpc.proto",
}

// WalletServerServiceClient is the client API for WalletServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServerServiceClient interface {
	// RegisterViewKey registers a new view key with the server. The server will use this key when
	// attempting to decrypt each output. If outputs decrypt, they will be indexed so the client
	// can fetch them later.
	//
	// To free up resources keys will automatically unregister after some time if the wallet has not
	// connected in some time.
	RegisterViewKey(ctx context.Context, in *RegisterViewKeyRequest, opts ...grpc.CallOption) (*RecomputeChainStateResponse, error)
	// SubscribeTransactions subscribes to a stream of TransactionsNotifications that match to the
	// provided view key.
	SubscribeTransactions(ctx context.Context, in *SubscribeTransactionsRequest, opts ...grpc.CallOption) (WalletServerService_SubscribeTransactionsClient, error)
	// GetWalletTransactions returns a list of transactions for the provided view key.
	GetWalletTransactions(ctx context.Context, in *GetWalletTransactionsRequest, opts ...grpc.CallOption) (*GetWalletTransactionsResponse, error)
	// GetTxoProof returns the merkle inclusion proof for the given commitment. This information is needed
	// by the client to create the zero knowledge proof needed to spend the transaction.
	GetTxoProof(ctx context.Context, in *GetTxoProofRequest, opts ...grpc.CallOption) (*GetTxoProofResponse, error)
}

type walletServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServerServiceClient(cc grpc.ClientConnInterface) WalletServerServiceClient {
	return &walletServerServiceClient{cc}
}

func (c *walletServerServiceClient) RegisterViewKey(ctx context.Context, in *RegisterViewKeyRequest, opts ...grpc.CallOption) (*RecomputeChainStateResponse, error) {
	out := new(RecomputeChainStateResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletServerService/RegisterViewKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServerServiceClient) SubscribeTransactions(ctx context.Context, in *SubscribeTransactionsRequest, opts ...grpc.CallOption) (WalletServerService_SubscribeTransactionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &WalletServerService_ServiceDesc.Streams[0], "/pb.WalletServerService/SubscribeTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &walletServerServiceSubscribeTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WalletServerService_SubscribeTransactionsClient interface {
	Recv() (*TransactionNotification, error)
	grpc.ClientStream
}

type walletServerServiceSubscribeTransactionsClient struct {
	grpc.ClientStream
}

func (x *walletServerServiceSubscribeTransactionsClient) Recv() (*TransactionNotification, error) {
	m := new(TransactionNotification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *walletServerServiceClient) GetWalletTransactions(ctx context.Context, in *GetWalletTransactionsRequest, opts ...grpc.CallOption) (*GetWalletTransactionsResponse, error) {
	out := new(GetWalletTransactionsResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletServerService/GetWalletTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServerServiceClient) GetTxoProof(ctx context.Context, in *GetTxoProofRequest, opts ...grpc.CallOption) (*GetTxoProofResponse, error) {
	out := new(GetTxoProofResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletServerService/GetTxoProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServerServiceServer is the server API for WalletServerService service.
// All implementations must embed UnimplementedWalletServerServiceServer
// for forward compatibility
type WalletServerServiceServer interface {
	// RegisterViewKey registers a new view key with the server. The server will use this key when
	// attempting to decrypt each output. If outputs decrypt, they will be indexed so the client
	// can fetch them later.
	//
	// To free up resources keys will automatically unregister after some time if the wallet has not
	// connected in some time.
	RegisterViewKey(context.Context, *RegisterViewKeyRequest) (*RecomputeChainStateResponse, error)
	// SubscribeTransactions subscribes to a stream of TransactionsNotifications that match to the
	// provided view key.
	SubscribeTransactions(*SubscribeTransactionsRequest, WalletServerService_SubscribeTransactionsServer) error
	// GetWalletTransactions returns a list of transactions for the provided view key.
	GetWalletTransactions(context.Context, *GetWalletTransactionsRequest) (*GetWalletTransactionsResponse, error)
	// GetTxoProof returns the merkle inclusion proof for the given commitment. This information is needed
	// by the client to create the zero knowledge proof needed to spend the transaction.
	GetTxoProof(context.Context, *GetTxoProofRequest) (*GetTxoProofResponse, error)
	mustEmbedUnimplementedWalletServerServiceServer()
}

// UnimplementedWalletServerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServerServiceServer struct {
}

func (UnimplementedWalletServerServiceServer) RegisterViewKey(context.Context, *RegisterViewKeyRequest) (*RecomputeChainStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterViewKey not implemented")
}
func (UnimplementedWalletServerServiceServer) SubscribeTransactions(*SubscribeTransactionsRequest, WalletServerService_SubscribeTransactionsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTransactions not implemented")
}
func (UnimplementedWalletServerServiceServer) GetWalletTransactions(context.Context, *GetWalletTransactionsRequest) (*GetWalletTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletTransactions not implemented")
}
func (UnimplementedWalletServerServiceServer) GetTxoProof(context.Context, *GetTxoProofRequest) (*GetTxoProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxoProof not implemented")
}
func (UnimplementedWalletServerServiceServer) mustEmbedUnimplementedWalletServerServiceServer() {}

// UnsafeWalletServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServerServiceServer will
// result in compilation errors.
type UnsafeWalletServerServiceServer interface {
	mustEmbedUnimplementedWalletServerServiceServer()
}

func RegisterWalletServerServiceServer(s grpc.ServiceRegistrar, srv WalletServerServiceServer) {
	s.RegisterService(&WalletServerService_ServiceDesc, srv)
}

func _WalletServerService_RegisterViewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterViewKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServerServiceServer).RegisterViewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletServerService/RegisterViewKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServerServiceServer).RegisterViewKey(ctx, req.(*RegisterViewKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletServerService_SubscribeTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalletServerServiceServer).SubscribeTransactions(m, &walletServerServiceSubscribeTransactionsServer{stream})
}

type WalletServerService_SubscribeTransactionsServer interface {
	Send(*TransactionNotification) error
	grpc.ServerStream
}

type walletServerServiceSubscribeTransactionsServer struct {
	grpc.ServerStream
}

func (x *walletServerServiceSubscribeTransactionsServer) Send(m *TransactionNotification) error {
	return x.ServerStream.SendMsg(m)
}

func _WalletServerService_GetWalletTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServerServiceServer).GetWalletTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletServerService/GetWalletTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServerServiceServer).GetWalletTransactions(ctx, req.(*GetWalletTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletServerService_GetTxoProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxoProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServerServiceServer).GetTxoProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletServerService/GetTxoProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServerServiceServer).GetTxoProof(ctx, req.(*GetTxoProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletServerService_ServiceDesc is the grpc.ServiceDesc for WalletServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WalletServerService",
	HandlerType: (*WalletServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterViewKey",
			Handler:    _WalletServerService_RegisterViewKey_Handler,
		},
		{
			MethodName: "GetWalletTransactions",
			Handler:    _WalletServerService_GetWalletTransactions_Handler,
		},
		{
			MethodName: "GetTxoProof",
			Handler:    _WalletServerService_GetTxoProof_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTransactions",
			Handler:       _WalletServerService_SubscribeTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ilxrpc.proto",
}

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	GetWalletSeed(ctx context.Context, in *GetWalletSeedRequest, opts ...grpc.CallOption) (*GetWalletSeedResponse, error)
	GetAddresses(ctx context.Context, in *GetAddressesRequest, opts ...grpc.CallOption) (*GetAddressesResponse, error)
	GetNewAddress(ctx context.Context, in *GetNewAddressRequest, opts ...grpc.CallOption) (*GetNewAddressResponse, error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error)
	GetUtxos(ctx context.Context, in *GetUtxosRequest, opts ...grpc.CallOption) (*GetUtxosResponse, error)
	GetPrivateKey(ctx context.Context, in *GetPrivateKeyRequest, opts ...grpc.CallOption) (*GetPrivateKeyResponse, error)
	ImportAddress(ctx context.Context, in *ImportAddressRequest, opts ...grpc.CallOption) (*ImportAddressResponse, error)
	CreateMultisigAddress(ctx context.Context, in *CreateMultisigAddressRequest, opts ...grpc.CallOption) (*CreateMultisigAddressResponse, error)
	ProveMultisig(ctx context.Context, in *ProveMultisigRequest, opts ...grpc.CallOption) (*ProveMultisigResponse, error)
	WalletLock(ctx context.Context, in *WalletLockRequest, opts ...grpc.CallOption) (*WalletUnlockRequest, error)
	WalletUnlock(ctx context.Context, in *WalletUnlockRequest, opts ...grpc.CallOption) (*WalletUnlockResponse, error)
	ChangeWalletPassphrase(ctx context.Context, in *ChangeWalletPassphraseRequest, opts ...grpc.CallOption) (*ChangeWalletPassphraseResponse, error)
	DeletePrivateKeys(ctx context.Context, in *DeletePrivateKeysRequest, opts ...grpc.CallOption) (*DeletePrivateKeysResponse, error)
	CreateRawTransaction(ctx context.Context, in *CreateRawTransactionRequest, opts ...grpc.CallOption) (*CreateRawTransactionResponse, error)
	ProveRawTransaction(ctx context.Context, in *ProveRawTransactionRequest, opts ...grpc.CallOption) (*ProveRawTransactionRequest, error)
	BroadcastRawTransaction(ctx context.Context, in *BroadcastRawTransactionRequest, opts ...grpc.CallOption) (*BroadcastRawTransactionResponse, error)
	Stake(ctx context.Context, in *StakeRequest, opts ...grpc.CallOption) (*StakeResponse, error)
	SetAutoStakeRewards(ctx context.Context, in *SetAutoStakeRewardsRequest, opts ...grpc.CallOption) (*SetAutoStakeRewardsResponse, error)
	Spend(ctx context.Context, in *SpendRequest, opts ...grpc.CallOption) (*SpendResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletSeed(ctx context.Context, in *GetWalletSeedRequest, opts ...grpc.CallOption) (*GetWalletSeedResponse, error) {
	out := new(GetWalletSeedResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/GetWalletSeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetAddresses(ctx context.Context, in *GetAddressesRequest, opts ...grpc.CallOption) (*GetAddressesResponse, error) {
	out := new(GetAddressesResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/GetAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetNewAddress(ctx context.Context, in *GetNewAddressRequest, opts ...grpc.CallOption) (*GetNewAddressResponse, error) {
	out := new(GetNewAddressResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/GetNewAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error) {
	out := new(GetTransactionsResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetUtxos(ctx context.Context, in *GetUtxosRequest, opts ...grpc.CallOption) (*GetUtxosResponse, error) {
	out := new(GetUtxosResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/GetUtxos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetPrivateKey(ctx context.Context, in *GetPrivateKeyRequest, opts ...grpc.CallOption) (*GetPrivateKeyResponse, error) {
	out := new(GetPrivateKeyResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/GetPrivateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ImportAddress(ctx context.Context, in *ImportAddressRequest, opts ...grpc.CallOption) (*ImportAddressResponse, error) {
	out := new(ImportAddressResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/ImportAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateMultisigAddress(ctx context.Context, in *CreateMultisigAddressRequest, opts ...grpc.CallOption) (*CreateMultisigAddressResponse, error) {
	out := new(CreateMultisigAddressResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/CreateMultisigAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ProveMultisig(ctx context.Context, in *ProveMultisigRequest, opts ...grpc.CallOption) (*ProveMultisigResponse, error) {
	out := new(ProveMultisigResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/ProveMultisig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) WalletLock(ctx context.Context, in *WalletLockRequest, opts ...grpc.CallOption) (*WalletUnlockRequest, error) {
	out := new(WalletUnlockRequest)
	err := c.cc.Invoke(ctx, "/pb.WalletService/WalletLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) WalletUnlock(ctx context.Context, in *WalletUnlockRequest, opts ...grpc.CallOption) (*WalletUnlockResponse, error) {
	out := new(WalletUnlockResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/WalletUnlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ChangeWalletPassphrase(ctx context.Context, in *ChangeWalletPassphraseRequest, opts ...grpc.CallOption) (*ChangeWalletPassphraseResponse, error) {
	out := new(ChangeWalletPassphraseResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/ChangeWalletPassphrase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) DeletePrivateKeys(ctx context.Context, in *DeletePrivateKeysRequest, opts ...grpc.CallOption) (*DeletePrivateKeysResponse, error) {
	out := new(DeletePrivateKeysResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/DeletePrivateKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) CreateRawTransaction(ctx context.Context, in *CreateRawTransactionRequest, opts ...grpc.CallOption) (*CreateRawTransactionResponse, error) {
	out := new(CreateRawTransactionResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/CreateRawTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ProveRawTransaction(ctx context.Context, in *ProveRawTransactionRequest, opts ...grpc.CallOption) (*ProveRawTransactionRequest, error) {
	out := new(ProveRawTransactionRequest)
	err := c.cc.Invoke(ctx, "/pb.WalletService/ProveRawTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) BroadcastRawTransaction(ctx context.Context, in *BroadcastRawTransactionRequest, opts ...grpc.CallOption) (*BroadcastRawTransactionResponse, error) {
	out := new(BroadcastRawTransactionResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/BroadcastRawTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Stake(ctx context.Context, in *StakeRequest, opts ...grpc.CallOption) (*StakeResponse, error) {
	out := new(StakeResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/Stake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SetAutoStakeRewards(ctx context.Context, in *SetAutoStakeRewardsRequest, opts ...grpc.CallOption) (*SetAutoStakeRewardsResponse, error) {
	out := new(SetAutoStakeRewardsResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/SetAutoStakeRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Spend(ctx context.Context, in *SpendRequest, opts ...grpc.CallOption) (*SpendResponse, error) {
	out := new(SpendResponse)
	err := c.cc.Invoke(ctx, "/pb.WalletService/Spend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility
type WalletServiceServer interface {
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	GetWalletSeed(context.Context, *GetWalletSeedRequest) (*GetWalletSeedResponse, error)
	GetAddresses(context.Context, *GetAddressesRequest) (*GetAddressesResponse, error)
	GetNewAddress(context.Context, *GetNewAddressRequest) (*GetNewAddressResponse, error)
	GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error)
	GetUtxos(context.Context, *GetUtxosRequest) (*GetUtxosResponse, error)
	GetPrivateKey(context.Context, *GetPrivateKeyRequest) (*GetPrivateKeyResponse, error)
	ImportAddress(context.Context, *ImportAddressRequest) (*ImportAddressResponse, error)
	CreateMultisigAddress(context.Context, *CreateMultisigAddressRequest) (*CreateMultisigAddressResponse, error)
	ProveMultisig(context.Context, *ProveMultisigRequest) (*ProveMultisigResponse, error)
	WalletLock(context.Context, *WalletLockRequest) (*WalletUnlockRequest, error)
	WalletUnlock(context.Context, *WalletUnlockRequest) (*WalletUnlockResponse, error)
	ChangeWalletPassphrase(context.Context, *ChangeWalletPassphraseRequest) (*ChangeWalletPassphraseResponse, error)
	DeletePrivateKeys(context.Context, *DeletePrivateKeysRequest) (*DeletePrivateKeysResponse, error)
	CreateRawTransaction(context.Context, *CreateRawTransactionRequest) (*CreateRawTransactionResponse, error)
	ProveRawTransaction(context.Context, *ProveRawTransactionRequest) (*ProveRawTransactionRequest, error)
	BroadcastRawTransaction(context.Context, *BroadcastRawTransactionRequest) (*BroadcastRawTransactionResponse, error)
	Stake(context.Context, *StakeRequest) (*StakeResponse, error)
	SetAutoStakeRewards(context.Context, *SetAutoStakeRewardsRequest) (*SetAutoStakeRewardsResponse, error)
	Spend(context.Context, *SpendRequest) (*SpendResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (UnimplementedWalletServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedWalletServiceServer) GetWalletSeed(context.Context, *GetWalletSeedRequest) (*GetWalletSeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletSeed not implemented")
}
func (UnimplementedWalletServiceServer) GetAddresses(context.Context, *GetAddressesRequest) (*GetAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddresses not implemented")
}
func (UnimplementedWalletServiceServer) GetNewAddress(context.Context, *GetNewAddressRequest) (*GetNewAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewAddress not implemented")
}
func (UnimplementedWalletServiceServer) GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedWalletServiceServer) GetUtxos(context.Context, *GetUtxosRequest) (*GetUtxosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUtxos not implemented")
}
func (UnimplementedWalletServiceServer) GetPrivateKey(context.Context, *GetPrivateKeyRequest) (*GetPrivateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateKey not implemented")
}
func (UnimplementedWalletServiceServer) ImportAddress(context.Context, *ImportAddressRequest) (*ImportAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportAddress not implemented")
}
func (UnimplementedWalletServiceServer) CreateMultisigAddress(context.Context, *CreateMultisigAddressRequest) (*CreateMultisigAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMultisigAddress not implemented")
}
func (UnimplementedWalletServiceServer) ProveMultisig(context.Context, *ProveMultisigRequest) (*ProveMultisigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveMultisig not implemented")
}
func (UnimplementedWalletServiceServer) WalletLock(context.Context, *WalletLockRequest) (*WalletUnlockRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletLock not implemented")
}
func (UnimplementedWalletServiceServer) WalletUnlock(context.Context, *WalletUnlockRequest) (*WalletUnlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletUnlock not implemented")
}
func (UnimplementedWalletServiceServer) ChangeWalletPassphrase(context.Context, *ChangeWalletPassphraseRequest) (*ChangeWalletPassphraseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeWalletPassphrase not implemented")
}
func (UnimplementedWalletServiceServer) DeletePrivateKeys(context.Context, *DeletePrivateKeysRequest) (*DeletePrivateKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePrivateKeys not implemented")
}
func (UnimplementedWalletServiceServer) CreateRawTransaction(context.Context, *CreateRawTransactionRequest) (*CreateRawTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRawTransaction not implemented")
}
func (UnimplementedWalletServiceServer) ProveRawTransaction(context.Context, *ProveRawTransactionRequest) (*ProveRawTransactionRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveRawTransaction not implemented")
}
func (UnimplementedWalletServiceServer) BroadcastRawTransaction(context.Context, *BroadcastRawTransactionRequest) (*BroadcastRawTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastRawTransaction not implemented")
}
func (UnimplementedWalletServiceServer) Stake(context.Context, *StakeRequest) (*StakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stake not implemented")
}
func (UnimplementedWalletServiceServer) SetAutoStakeRewards(context.Context, *SetAutoStakeRewardsRequest) (*SetAutoStakeRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAutoStakeRewards not implemented")
}
func (UnimplementedWalletServiceServer) Spend(context.Context, *SpendRequest) (*SpendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Spend not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/GetWalletSeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletSeed(ctx, req.(*GetWalletSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/GetAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetAddresses(ctx, req.(*GetAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetNewAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetNewAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/GetNewAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetNewAddress(ctx, req.(*GetNewAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetUtxos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUtxosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetUtxos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/GetUtxos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetUtxos(ctx, req.(*GetUtxosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetPrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetPrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/GetPrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetPrivateKey(ctx, req.(*GetPrivateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ImportAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ImportAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/ImportAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ImportAddress(ctx, req.(*ImportAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateMultisigAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMultisigAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateMultisigAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/CreateMultisigAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateMultisigAddress(ctx, req.(*CreateMultisigAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ProveMultisig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveMultisigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ProveMultisig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/ProveMultisig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ProveMultisig(ctx, req.(*ProveMultisigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_WalletLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).WalletLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/WalletLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).WalletLock(ctx, req.(*WalletLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_WalletUnlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletUnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).WalletUnlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/WalletUnlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).WalletUnlock(ctx, req.(*WalletUnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ChangeWalletPassphrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeWalletPassphraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ChangeWalletPassphrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/ChangeWalletPassphrase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ChangeWalletPassphrase(ctx, req.(*ChangeWalletPassphraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_DeletePrivateKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePrivateKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).DeletePrivateKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/DeletePrivateKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).DeletePrivateKeys(ctx, req.(*DeletePrivateKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_CreateRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRawTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/CreateRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateRawTransaction(ctx, req.(*CreateRawTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ProveRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveRawTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ProveRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/ProveRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ProveRawTransaction(ctx, req.(*ProveRawTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_BroadcastRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRawTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).BroadcastRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/BroadcastRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).BroadcastRawTransaction(ctx, req.(*BroadcastRawTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Stake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Stake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/Stake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Stake(ctx, req.(*StakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SetAutoStakeRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAutoStakeRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SetAutoStakeRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/SetAutoStakeRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SetAutoStakeRewards(ctx, req.(*SetAutoStakeRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Spend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Spend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WalletService/Spend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Spend(ctx, req.(*SpendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _WalletService_GetBalance_Handler,
		},
		{
			MethodName: "GetWalletSeed",
			Handler:    _WalletService_GetWalletSeed_Handler,
		},
		{
			MethodName: "GetAddresses",
			Handler:    _WalletService_GetAddresses_Handler,
		},
		{
			MethodName: "GetNewAddress",
			Handler:    _WalletService_GetNewAddress_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _WalletService_GetTransactions_Handler,
		},
		{
			MethodName: "GetUtxos",
			Handler:    _WalletService_GetUtxos_Handler,
		},
		{
			MethodName: "GetPrivateKey",
			Handler:    _WalletService_GetPrivateKey_Handler,
		},
		{
			MethodName: "ImportAddress",
			Handler:    _WalletService_ImportAddress_Handler,
		},
		{
			MethodName: "CreateMultisigAddress",
			Handler:    _WalletService_CreateMultisigAddress_Handler,
		},
		{
			MethodName: "ProveMultisig",
			Handler:    _WalletService_ProveMultisig_Handler,
		},
		{
			MethodName: "WalletLock",
			Handler:    _WalletService_WalletLock_Handler,
		},
		{
			MethodName: "WalletUnlock",
			Handler:    _WalletService_WalletUnlock_Handler,
		},
		{
			MethodName: "ChangeWalletPassphrase",
			Handler:    _WalletService_ChangeWalletPassphrase_Handler,
		},
		{
			MethodName: "DeletePrivateKeys",
			Handler:    _WalletService_DeletePrivateKeys_Handler,
		},
		{
			MethodName: "CreateRawTransaction",
			Handler:    _WalletService_CreateRawTransaction_Handler,
		},
		{
			MethodName: "ProveRawTransaction",
			Handler:    _WalletService_ProveRawTransaction_Handler,
		},
		{
			MethodName: "BroadcastRawTransaction",
			Handler:    _WalletService_BroadcastRawTransaction_Handler,
		},
		{
			MethodName: "Stake",
			Handler:    _WalletService_Stake_Handler,
		},
		{
			MethodName: "SetAutoStakeRewards",
			Handler:    _WalletService_SetAutoStakeRewards_Handler,
		},
		{
			MethodName: "Spend",
			Handler:    _WalletService_Spend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ilxrpc.proto",
}

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error)
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error)
	AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error)
	BlockPeer(ctx context.Context, in *BlockPeerRequest, opts ...grpc.CallOption) (*BlockPeerResponse, error)
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error)
	GetMinFeePerByte(ctx context.Context, in *GetMinFeePerByteRequest, opts ...grpc.CallOption) (*GetMinFeePerByteResponse, error)
	SetMinFeePerByte(ctx context.Context, in *SetMinFeePerByteRequest, opts ...grpc.CallOption) (*SetMinFeePerByteResponse, error)
	GetMinStake(ctx context.Context, in *GetMinStakeRequest, opts ...grpc.CallOption) (*GetMinStakeResponse, error)
	SetMinStake(ctx context.Context, in *SetMinStakeRequest, opts ...grpc.CallOption) (*SetMinStakeResponse, error)
	GetBlockSizeSoftLimit(ctx context.Context, in *GetBlockSizeSoftLimitRequest, opts ...grpc.CallOption) (*GetBlockSizeSoftLimitResponse, error)
	SetBlockSizeSoftLimit(ctx context.Context, in *SetBlockSizeSoftLimitRequest, opts ...grpc.CallOption) (*SetBlockSizeSoftLimitResponse, error)
	GetTreasuryWhitelist(ctx context.Context, in *GetTreasuryWhitelistRequest, opts ...grpc.CallOption) (*GetTreasuryWhitelistResponse, error)
	WhitelistTreasuryTransaction(ctx context.Context, in *WhitelistTreasuryTransactionRequest, opts ...grpc.CallOption) (*WhitelistTreasuryTransactionResponse, error)
	ReconsiderBlock(ctx context.Context, in *ReconsiderBlockRequest, opts ...grpc.CallOption) (*ReconsiderBlockResponse, error)
	RecomputeChainState(ctx context.Context, in *RecomputeChainStateRequest, opts ...grpc.CallOption) (*RecomputeChainStateResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error) {
	out := new(GetHostInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/GetHostInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/GetPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error) {
	out := new(AddPeerResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/AddPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) BlockPeer(ctx context.Context, in *BlockPeerRequest, opts ...grpc.CallOption) (*BlockPeerResponse, error) {
	out := new(BlockPeerResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/BlockPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error) {
	out := new(SetLogLevelResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/SetLogLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetMinFeePerByte(ctx context.Context, in *GetMinFeePerByteRequest, opts ...grpc.CallOption) (*GetMinFeePerByteResponse, error) {
	out := new(GetMinFeePerByteResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/GetMinFeePerByte", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetMinFeePerByte(ctx context.Context, in *SetMinFeePerByteRequest, opts ...grpc.CallOption) (*SetMinFeePerByteResponse, error) {
	out := new(SetMinFeePerByteResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/SetMinFeePerByte", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetMinStake(ctx context.Context, in *GetMinStakeRequest, opts ...grpc.CallOption) (*GetMinStakeResponse, error) {
	out := new(GetMinStakeResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/GetMinStake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetMinStake(ctx context.Context, in *SetMinStakeRequest, opts ...grpc.CallOption) (*SetMinStakeResponse, error) {
	out := new(SetMinStakeResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/SetMinStake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetBlockSizeSoftLimit(ctx context.Context, in *GetBlockSizeSoftLimitRequest, opts ...grpc.CallOption) (*GetBlockSizeSoftLimitResponse, error) {
	out := new(GetBlockSizeSoftLimitResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/GetBlockSizeSoftLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetBlockSizeSoftLimit(ctx context.Context, in *SetBlockSizeSoftLimitRequest, opts ...grpc.CallOption) (*SetBlockSizeSoftLimitResponse, error) {
	out := new(SetBlockSizeSoftLimitResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/SetBlockSizeSoftLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetTreasuryWhitelist(ctx context.Context, in *GetTreasuryWhitelistRequest, opts ...grpc.CallOption) (*GetTreasuryWhitelistResponse, error) {
	out := new(GetTreasuryWhitelistResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/GetTreasuryWhitelist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WhitelistTreasuryTransaction(ctx context.Context, in *WhitelistTreasuryTransactionRequest, opts ...grpc.CallOption) (*WhitelistTreasuryTransactionResponse, error) {
	out := new(WhitelistTreasuryTransactionResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/WhitelistTreasuryTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReconsiderBlock(ctx context.Context, in *ReconsiderBlockRequest, opts ...grpc.CallOption) (*ReconsiderBlockResponse, error) {
	out := new(ReconsiderBlockResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/ReconsiderBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RecomputeChainState(ctx context.Context, in *RecomputeChainStateRequest, opts ...grpc.CallOption) (*RecomputeChainStateResponse, error) {
	out := new(RecomputeChainStateResponse)
	err := c.cc.Invoke(ctx, "/pb.NodeService/RecomputeChainState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error)
	GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error)
	AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error)
	BlockPeer(context.Context, *BlockPeerRequest) (*BlockPeerResponse, error)
	SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error)
	GetMinFeePerByte(context.Context, *GetMinFeePerByteRequest) (*GetMinFeePerByteResponse, error)
	SetMinFeePerByte(context.Context, *SetMinFeePerByteRequest) (*SetMinFeePerByteResponse, error)
	GetMinStake(context.Context, *GetMinStakeRequest) (*GetMinStakeResponse, error)
	SetMinStake(context.Context, *SetMinStakeRequest) (*SetMinStakeResponse, error)
	GetBlockSizeSoftLimit(context.Context, *GetBlockSizeSoftLimitRequest) (*GetBlockSizeSoftLimitResponse, error)
	SetBlockSizeSoftLimit(context.Context, *SetBlockSizeSoftLimitRequest) (*SetBlockSizeSoftLimitResponse, error)
	GetTreasuryWhitelist(context.Context, *GetTreasuryWhitelistRequest) (*GetTreasuryWhitelistResponse, error)
	WhitelistTreasuryTransaction(context.Context, *WhitelistTreasuryTransactionRequest) (*WhitelistTreasuryTransactionResponse, error)
	ReconsiderBlock(context.Context, *ReconsiderBlockRequest) (*ReconsiderBlockResponse, error)
	RecomputeChainState(context.Context, *RecomputeChainStateRequest) (*RecomputeChainStateResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostInfo not implemented")
}
func (UnimplementedNodeServiceServer) GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedNodeServiceServer) AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPeer not implemented")
}
func (UnimplementedNodeServiceServer) BlockPeer(context.Context, *BlockPeerRequest) (*BlockPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockPeer not implemented")
}
func (UnimplementedNodeServiceServer) SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedNodeServiceServer) GetMinFeePerByte(context.Context, *GetMinFeePerByteRequest) (*GetMinFeePerByteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinFeePerByte not implemented")
}
func (UnimplementedNodeServiceServer) SetMinFeePerByte(context.Context, *SetMinFeePerByteRequest) (*SetMinFeePerByteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMinFeePerByte not implemented")
}
func (UnimplementedNodeServiceServer) GetMinStake(context.Context, *GetMinStakeRequest) (*GetMinStakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinStake not implemented")
}
func (UnimplementedNodeServiceServer) SetMinStake(context.Context, *SetMinStakeRequest) (*SetMinStakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMinStake not implemented")
}
func (UnimplementedNodeServiceServer) GetBlockSizeSoftLimit(context.Context, *GetBlockSizeSoftLimitRequest) (*GetBlockSizeSoftLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockSizeSoftLimit not implemented")
}
func (UnimplementedNodeServiceServer) SetBlockSizeSoftLimit(context.Context, *SetBlockSizeSoftLimitRequest) (*SetBlockSizeSoftLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBlockSizeSoftLimit not implemented")
}
func (UnimplementedNodeServiceServer) GetTreasuryWhitelist(context.Context, *GetTreasuryWhitelistRequest) (*GetTreasuryWhitelistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTreasuryWhitelist not implemented")
}
func (UnimplementedNodeServiceServer) WhitelistTreasuryTransaction(context.Context, *WhitelistTreasuryTransactionRequest) (*WhitelistTreasuryTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhitelistTreasuryTransaction not implemented")
}
func (UnimplementedNodeServiceServer) ReconsiderBlock(context.Context, *ReconsiderBlockRequest) (*ReconsiderBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReconsiderBlock not implemented")
}
func (UnimplementedNodeServiceServer) RecomputeChainState(context.Context, *RecomputeChainStateRequest) (*RecomputeChainStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecomputeChainState not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GetHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/GetHostInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetHostInfo(ctx, req.(*GetHostInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/GetPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetPeers(ctx, req.(*GetPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/AddPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AddPeer(ctx, req.(*AddPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_BlockPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).BlockPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/BlockPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).BlockPeer(ctx, req.(*BlockPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/SetLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetLogLevel(ctx, req.(*SetLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetMinFeePerByte_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMinFeePerByteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetMinFeePerByte(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/GetMinFeePerByte",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetMinFeePerByte(ctx, req.(*GetMinFeePerByteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetMinFeePerByte_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMinFeePerByteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetMinFeePerByte(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/SetMinFeePerByte",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetMinFeePerByte(ctx, req.(*SetMinFeePerByteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetMinStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMinStakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetMinStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/GetMinStake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetMinStake(ctx, req.(*GetMinStakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetMinStake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMinStakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetMinStake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/SetMinStake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetMinStake(ctx, req.(*SetMinStakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetBlockSizeSoftLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockSizeSoftLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetBlockSizeSoftLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/GetBlockSizeSoftLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetBlockSizeSoftLimit(ctx, req.(*GetBlockSizeSoftLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetBlockSizeSoftLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBlockSizeSoftLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetBlockSizeSoftLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/SetBlockSizeSoftLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetBlockSizeSoftLimit(ctx, req.(*SetBlockSizeSoftLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetTreasuryWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTreasuryWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetTreasuryWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/GetTreasuryWhitelist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetTreasuryWhitelist(ctx, req.(*GetTreasuryWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WhitelistTreasuryTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhitelistTreasuryTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).WhitelistTreasuryTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/WhitelistTreasuryTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).WhitelistTreasuryTransaction(ctx, req.(*WhitelistTreasuryTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReconsiderBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconsiderBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReconsiderBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/ReconsiderBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReconsiderBlock(ctx, req.(*ReconsiderBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RecomputeChainState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecomputeChainStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RecomputeChainState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NodeService/RecomputeChainState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RecomputeChainState(ctx, req.(*RecomputeChainStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHostInfo",
			Handler:    _NodeService_GetHostInfo_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _NodeService_GetPeers_Handler,
		},
		{
			MethodName: "AddPeer",
			Handler:    _NodeService_AddPeer_Handler,
		},
		{
			MethodName: "BlockPeer",
			Handler:    _NodeService_BlockPeer_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _NodeService_SetLogLevel_Handler,
		},
		{
			MethodName: "GetMinFeePerByte",
			Handler:    _NodeService_GetMinFeePerByte_Handler,
		},
		{
			MethodName: "SetMinFeePerByte",
			Handler:    _NodeService_SetMinFeePerByte_Handler,
		},
		{
			MethodName: "GetMinStake",
			Handler:    _NodeService_GetMinStake_Handler,
		},
		{
			MethodName: "SetMinStake",
			Handler:    _NodeService_SetMinStake_Handler,
		},
		{
			MethodName: "GetBlockSizeSoftLimit",
			Handler:    _NodeService_GetBlockSizeSoftLimit_Handler,
		},
		{
			MethodName: "SetBlockSizeSoftLimit",
			Handler:    _NodeService_SetBlockSizeSoftLimit_Handler,
		},
		{
			MethodName: "GetTreasuryWhitelist",
			Handler:    _NodeService_GetTreasuryWhitelist_Handler,
		},
		{
			MethodName: "WhitelistTreasuryTransaction",
			Handler:    _NodeService_WhitelistTreasuryTransaction_Handler,
		},
		{
			MethodName: "ReconsiderBlock",
			Handler:    _NodeService_ReconsiderBlock_Handler,
		},
		{
			MethodName: "RecomputeChainState",
			Handler:    _NodeService_RecomputeChainState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ilxrpc.proto",
}
