// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: db_indexer_models.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inputs  []*DBMetadata_IOMetadata `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs []*DBMetadata_IOMetadata `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (x *DBMetadata) Reset() {
	*x = DBMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_indexer_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMetadata) ProtoMessage() {}

func (x *DBMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_db_indexer_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMetadata.ProtoReflect.Descriptor instead.
func (*DBMetadata) Descriptor() ([]byte, []int) {
	return file_db_indexer_models_proto_rawDescGZIP(), []int{0}
}

func (x *DBMetadata) GetInputs() []*DBMetadata_IOMetadata {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *DBMetadata) GetOutputs() []*DBMetadata_IOMetadata {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type DBAddrAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *DBAddrAmount) Reset() {
	*x = DBAddrAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_indexer_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBAddrAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBAddrAmount) ProtoMessage() {}

func (x *DBAddrAmount) ProtoReflect() protoreflect.Message {
	mi := &file_db_indexer_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBAddrAmount.ProtoReflect.Descriptor instead.
func (*DBAddrAmount) Descriptor() ([]byte, []int) {
	return file_db_indexer_models_proto_rawDescGZIP(), []int{1}
}

func (x *DBAddrAmount) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DBAddrAmount) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DBMetadata_IOMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Either address/amount information or unknown
	// if input or output did not belong to this wallet
	// and can't be decrypted.
	//
	// Types that are assignable to IoType:
	//
	//	*DBMetadata_IOMetadata_TxIo
	//	*DBMetadata_IOMetadata_Unknown_
	IoType isDBMetadata_IOMetadata_IoType `protobuf_oneof:"io_type"`
}

func (x *DBMetadata_IOMetadata) Reset() {
	*x = DBMetadata_IOMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_indexer_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBMetadata_IOMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMetadata_IOMetadata) ProtoMessage() {}

func (x *DBMetadata_IOMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_db_indexer_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMetadata_IOMetadata.ProtoReflect.Descriptor instead.
func (*DBMetadata_IOMetadata) Descriptor() ([]byte, []int) {
	return file_db_indexer_models_proto_rawDescGZIP(), []int{0, 0}
}

func (m *DBMetadata_IOMetadata) GetIoType() isDBMetadata_IOMetadata_IoType {
	if m != nil {
		return m.IoType
	}
	return nil
}

func (x *DBMetadata_IOMetadata) GetTxIo() *DBMetadata_IOMetadata_TxIO {
	if x, ok := x.GetIoType().(*DBMetadata_IOMetadata_TxIo); ok {
		return x.TxIo
	}
	return nil
}

func (x *DBMetadata_IOMetadata) GetUnknown() *DBMetadata_IOMetadata_Unknown {
	if x, ok := x.GetIoType().(*DBMetadata_IOMetadata_Unknown_); ok {
		return x.Unknown
	}
	return nil
}

type isDBMetadata_IOMetadata_IoType interface {
	isDBMetadata_IOMetadata_IoType()
}

type DBMetadata_IOMetadata_TxIo struct {
	TxIo *DBMetadata_IOMetadata_TxIO `protobuf:"bytes,1,opt,name=tx_io,json=txIo,proto3,oneof"`
}

type DBMetadata_IOMetadata_Unknown_ struct {
	Unknown *DBMetadata_IOMetadata_Unknown `protobuf:"bytes,2,opt,name=unknown,proto3,oneof"`
}

func (*DBMetadata_IOMetadata_TxIo) isDBMetadata_IOMetadata_IoType() {}

func (*DBMetadata_IOMetadata_Unknown_) isDBMetadata_IOMetadata_IoType() {}

type DBMetadata_IOMetadata_TxIO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address associated with the input or output
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Amount of coins associated with the input or output in nanoillium
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *DBMetadata_IOMetadata_TxIO) Reset() {
	*x = DBMetadata_IOMetadata_TxIO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_indexer_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBMetadata_IOMetadata_TxIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMetadata_IOMetadata_TxIO) ProtoMessage() {}

func (x *DBMetadata_IOMetadata_TxIO) ProtoReflect() protoreflect.Message {
	mi := &file_db_indexer_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMetadata_IOMetadata_TxIO.ProtoReflect.Descriptor instead.
func (*DBMetadata_IOMetadata_TxIO) Descriptor() ([]byte, []int) {
	return file_db_indexer_models_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *DBMetadata_IOMetadata_TxIO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DBMetadata_IOMetadata_TxIO) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Represents an input or output not belonging to
// the wallet.
type DBMetadata_IOMetadata_Unknown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DBMetadata_IOMetadata_Unknown) Reset() {
	*x = DBMetadata_IOMetadata_Unknown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_indexer_models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBMetadata_IOMetadata_Unknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMetadata_IOMetadata_Unknown) ProtoMessage() {}

func (x *DBMetadata_IOMetadata_Unknown) ProtoReflect() protoreflect.Message {
	mi := &file_db_indexer_models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMetadata_IOMetadata_Unknown.ProtoReflect.Descriptor instead.
func (*DBMetadata_IOMetadata_Unknown) Descriptor() ([]byte, []int) {
	return file_db_indexer_models_proto_rawDescGZIP(), []int{0, 0, 1}
}

var File_db_indexer_models_proto protoreflect.FileDescriptor

var file_db_indexer_models_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x62, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x02, 0x0a, 0x0a, 0x44, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x44, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x49, 0x4f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x44, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x49, 0x4f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x1a, 0xcc, 0x01, 0x0a, 0x0a, 0x49,
	0x4f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x05, 0x74, 0x78, 0x5f,
	0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x44, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x49, 0x4f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x54, 0x78, 0x49, 0x4f, 0x48, 0x00, 0x52, 0x04, 0x74, 0x78, 0x49, 0x6f, 0x12, 0x3a, 0x0a,
	0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x44, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x49, 0x4f, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x48, 0x00,
	0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x1a, 0x38, 0x0a, 0x04, 0x54, 0x78, 0x49,
	0x4f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x1a, 0x09, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x42, 0x09,
	0x0a, 0x07, 0x69, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x44, 0x42, 0x41,
	0x64, 0x64, 0x72, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_indexer_models_proto_rawDescOnce sync.Once
	file_db_indexer_models_proto_rawDescData = file_db_indexer_models_proto_rawDesc
)

func file_db_indexer_models_proto_rawDescGZIP() []byte {
	file_db_indexer_models_proto_rawDescOnce.Do(func() {
		file_db_indexer_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_indexer_models_proto_rawDescData)
	})
	return file_db_indexer_models_proto_rawDescData
}

var file_db_indexer_models_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_db_indexer_models_proto_goTypes = []interface{}{
	(*DBMetadata)(nil),                    // 0: DBMetadata
	(*DBAddrAmount)(nil),                  // 1: DBAddrAmount
	(*DBMetadata_IOMetadata)(nil),         // 2: DBMetadata.IOMetadata
	(*DBMetadata_IOMetadata_TxIO)(nil),    // 3: DBMetadata.IOMetadata.TxIO
	(*DBMetadata_IOMetadata_Unknown)(nil), // 4: DBMetadata.IOMetadata.Unknown
}
var file_db_indexer_models_proto_depIdxs = []int32{
	2, // 0: DBMetadata.inputs:type_name -> DBMetadata.IOMetadata
	2, // 1: DBMetadata.outputs:type_name -> DBMetadata.IOMetadata
	3, // 2: DBMetadata.IOMetadata.tx_io:type_name -> DBMetadata.IOMetadata.TxIO
	4, // 3: DBMetadata.IOMetadata.unknown:type_name -> DBMetadata.IOMetadata.Unknown
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_db_indexer_models_proto_init() }
func file_db_indexer_models_proto_init() {
	if File_db_indexer_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_indexer_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_indexer_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBAddrAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_indexer_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBMetadata_IOMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_indexer_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBMetadata_IOMetadata_TxIO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_indexer_models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBMetadata_IOMetadata_Unknown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_db_indexer_models_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*DBMetadata_IOMetadata_TxIo)(nil),
		(*DBMetadata_IOMetadata_Unknown_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_indexer_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_indexer_models_proto_goTypes,
		DependencyIndexes: file_db_indexer_models_proto_depIdxs,
		MessageInfos:      file_db_indexer_models_proto_msgTypes,
	}.Build()
	File_db_indexer_models_proto = out.File
	file_db_indexer_models_proto_rawDesc = nil
	file_db_indexer_models_proto_goTypes = nil
	file_db_indexer_models_proto_depIdxs = nil
}
